import os
import time
from datetime import datetime
from fpdf import FPDF
import whois
import socket

class TakedownPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'TRINETRA CYBER DEFENSE SYSTEM', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Municipal Corporation of Delhi (MCD) - Official Takedown Notice', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Auto-generated by TRINETRA Database', 0, 0, 'C')

def generate_takedown_report(domain, classification, explanation, site_data=None, alerts=None):
    if site_data is None: site_data = {}
    if alerts is None: alerts = []

    # Retrieve IOCs safely
    try:
        ip_addr = socket.gethostbyname(domain)
    except:
        ip_addr = "Unknown/Unresolved"

    registrar = "Unknown"
    creation_date = "Unknown"
    expiration_date = "Unknown"
    
    try:
        w = whois.whois(domain)
        registrar = w.registrar if w.registrar else "Unknown"
        if w.creation_date:
            creation_date = str(w.creation_date[0] if isinstance(w.creation_date, list) else w.creation_date)
        if w.expiration_date:
            expiration_date = str(w.expiration_date[0] if isinstance(w.expiration_date, list) else w.expiration_date)
    except:
        pass

    pdf = TakedownPDF()
    pdf.add_page()
    
    # Metadata
    now = datetime.now()
    req_id = f"RPT-{now.strftime('%Y%m%d')}-{int(time.time())}"
    
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "TAKEDOWN REQUEST", ln=True, align="L")
    pdf.ln(5)
    
    pdf.set_font("Arial", size=11)
    # create a table-like structure
    pdf.cell(40, 8, "Date:", 0, 0)
    pdf.cell(0, 8, now.strftime('%d %B %Y, %I:%M %p'), 0, 1)
    
    pdf.cell(40, 8, "Reported By:", 0, 0)
    pdf.cell(0, 8, "TRINETRA Threat Intelligence, MCD", 0, 1)
    
    portal_type = site_data.get("portal_type", "MCD Services").replace("_", " ").title()
    pdf.cell(40, 8, "Target Portal:", 0, 0)
    pdf.cell(0, 8, portal_type, 0, 1)

    pdf.cell(40, 8, "Target Domain:", 0, 0)
    pdf.cell(0, 8, domain, 0, 1)

    pdf.cell(40, 8, "Incident Req ID:", 0, 0)
    pdf.cell(0, 8, req_id, 0, 1)

    pdf.ln(5)
    
    # Target Network Information
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "Target Network Information (IOCs)", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    
    pdf.set_font("Arial", size=11)
    pdf.cell(40, 8, "Resolving IP:", 0, 0)
    pdf.cell(0, 8, str(ip_addr), 0, 1)
    pdf.cell(40, 8, "Registrar:", 0, 0)
    pdf.cell(0, 8, str(registrar), 0, 1)
    pdf.cell(40, 8, "Creation Date:", 0, 0)
    pdf.cell(0, 8, creation_date, 0, 1)
    pdf.cell(40, 8, "Exp. Date:", 0, 0)
    pdf.cell(0, 8, expiration_date, 0, 1)
    
    pdf.ln(5)

    # Trinetra AI Analysis
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "Trinetra AI Analysis Engine", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_font("Arial", size=11)
    risk_score = site_data.get("score", site_data.get("composite_score", "N/A"))
    if isinstance(risk_score, (float, int)):
        risk_score = f"{risk_score}/100"
    
    visual_score = site_data.get("visual_score", "N/A")
    if isinstance(visual_score, (float, int)):
        visual_score = f"{visual_score}% match"

    html_score = site_data.get("html_score", "N/A")
    if isinstance(html_score, (float, int)):
        html_score = f"{html_score}/100"
        
    pdf.cell(40, 8, "Composite Score:", 0, 0)
    pdf.cell(0, 8, str(risk_score), 0, 1)
    pdf.cell(40, 8, "Visual Similarity:", 0, 0)
    pdf.cell(0, 8, str(visual_score), 0, 1)
    pdf.cell(40, 8, "HTML Heuristic:", 0, 0)
    pdf.cell(0, 8, str(html_score), 0, 1)
    pdf.cell(40, 8, "Detected By:", 0, 0)
    pdf.cell(0, 8, "Trinetra Core Proactive Model", 0, 1)

    pdf.ln(5)

    # Correlated Threats
    if alerts:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "Correlated Threat Activities", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(2)
        
        pdf.set_font("Arial", size=10)
        for idx, alert in enumerate(alerts[:3]):  # Show up to 3 alerts
            msg = alert.get("message", "Suspicious activity detected")
            sev = alert.get("severity", "UNKNOWN")
            pdf.multi_cell(0, 6, f"- [{sev}] {msg}")
        pdf.ln(5)

    # Forensic Canary Evidence
    canary = site_data.get("canary_username")
    if canary:
        pdf.set_font("Arial", 'B', 12)
        pdf.set_text_color(220, 20, 60) # Crimson red
        pdf.cell(0, 8, "FORENSIC EVIDENCE: INDISPUTABLE CREDENTIAL THEFT", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(2)
        
        pdf.set_font("Arial", size=10)
        pdf.multi_cell(0, 6, 
            "The TRINETRA system proactively deployed a tracking token (Canary Account) tied exclusively to this phishing domain. "
            f"The attacker attempted to use the stolen credential '{canary}' against official MCD infrastructure, proving malicious intent."
        )
        pdf.ln(5)

    # Evidence
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "Threat Intelligence & Evidence", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.set_text_color(200, 0, 0)
    pdf.cell(40, 8, "CLASSIFICATION:", 0, 0)
    pdf.cell(0, 8, classification, 0, 1)
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_font("Arial", size=11)
    pdf.cell(0, 8, "EVIDENCE:", ln=True)
    pdf.multi_cell(0, 6, explanation)
    
    pdf.ln(8)
    
    # Check for screenshot in data/screenshots or backend/screenshots
    base_dir = os.path.dirname(os.path.abspath(__file__))
    screenshot_path = os.path.join(base_dir, "screenshots", f"{domain}.png")
    
    if os.path.exists(screenshot_path):
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(0, 8, "Visual Evidence (Screenshot):", ln=True)
        try:
            pdf.image(screenshot_path, w=150)
            pdf.ln(5)
        except Exception as e:
            pdf.set_font("Arial", size=10)
            pdf.cell(0, 8, f"[Screenshot embedding failed: {e}]", ln=True)
    
    # Statutory Notice
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "Statutory Legal Notice", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Arial", size=11)
    legal_text = (
        "This domain was detected proactively impersonating an official MCD government portal. "
        "Immediate takedown is requested under Section 66A/66C of the Information Technology Act, 2000. "
        "Please remove this domain and associated SSL certificate immediately."
    )
    pdf.multi_cell(0, 6, legal_text)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, "Contact: cybersecurity@mcd.gov.in", ln=True)

    # Make output dir
    output_dir = os.path.join(base_dir, "data", "reports")
    os.makedirs(output_dir, exist_ok=True)
    
    clean_domain = domain.replace('.', '_').replace(':', '_').replace('/', '')
    pdf_path = os.path.join(output_dir, f"{clean_domain}_takedown.pdf")
    pdf.output(pdf_path)
    
    return pdf_path
